### ISSUE TITLE
Used Memeory % Almost Twice as High as System Shows

### ISSUE THREAD

**Issue by rogueops** [lcdproc/lcdproc#108]
Just need to know what code to look at to see why the LCD mem used % is about twice as much as top, the webgui, and a memory stats pearl script shows.

**Comment by haraldg** [comment]
Is this a problem with gathering the data or with displaying the data?
Maybe this is related to #59 ?

**Comment by haraldg** [comment]
The mem screen got havily reworked in #120. Also no actual details about the problem have ever been provided. Thus closing this issue as obsolete. If there is still some problem, please reopen and provide additional information.
