### ISSUE TITLE
hd44780-usb4all hardware initialisation wrong way around?

### ISSUE THREAD

**Issue by scp38** [lcdproc/lcdproc#144]
Dear all,

after running lcdproc for many years in hd44780-winamp mode I had to switch the mainboard and so had no parallel port any more. So I changed over to usb4-all since it offers also support for my 6 button keyboard.

After compiling (and yes, including the files for libusb-0.1) I noticed that the display only worked fine after the second start of the LCDd service.

I found in the hd44780-usb4all.c that the display initialisation is done BEFORE the USB4all-interface initialisation. So only after the second start of LCDd service, the display was correctly initialized.

IMHO there should be a change from 

	common_init(p, IF_4BIT);

	/* replace uPause with empty one after initialization */
	p->hd44780_functions->uPause = usb4all_HD44780_uPause;

	/* initialize usb-4-all controller */
	usb4all_init(p);

to 

	/* initialize usb-4-all controller */
	usb4all_init(p);

	common_init(p, IF_4BIT);

	/* replace uPause with empty one after initialization */
	p->hd44780_functions->uPause = usb4all_HD44780_uPause;

At least this code works for me now with the very first start of the LCDd service.

Regards,
Paul

**Comment by haraldg** [comment]
@ThoMo I believe this is your driver. Can you comment on this?

**Comment by thomo** [comment]
Never mentioned the issue before (at least I can't remember) and I also can't test it now (I do not use it anymore). Any way - after looking in the code the suggested change sounds reasonable to me.

**Comment by scp38** [comment]
Wow! Thank you very much for your quick feedback. Very much appreciated!
