### ISSUE TITLE
problem with serdisplib

### ISSUE THREAD

**Issue by preguntitas** [lcdproc/lcdproc#162]
Hello,

I am trying to get my lcd (alphacool 240x128p) to work using lcdproc on my Arch linux.

I have first used the package from the arch repository, but it has not worked. So I have downloaded the source from github and compiled it following the instructions;

1. compilation:
```
sh autogen.sh
./configure --enable-libusb --enable-drivers = all
make
```

2. configuration file(LCDd.conf):
```
[server]
DriverPath=/home/preguntitas/lcdproc/lcdproc/server/drivers/
Driver=glcd
Bind=127.0.0.1
Port=13666
User=nobody
WaitTime=5
ServerScreen=no
Foreground=no
Backlight=open

[glcd]
ConnectionType='serdisplib'
Size=240x128
CellSize=10x16
useFT2=yes
normal_font=/usr/share/fonts/liberation/LiberationMono-Bold.ttf
serdisp_name=ALPHACOOL
serdisp_device=USB:060C/04EB
```

3. Running

```
[preguntitas@Piccolo server]$ $PWD/LCDd -c LCDd.conf 
glcd: unknown ConnectionType: 'serdisplib'
Driver [glcd] init failed, return code -1
Could not load driver glcd
There is no output driver
Critical error while initializing, abort.
```

glcd does not seem to accept being serdisplib. same error as with the repository version.

Can somebody help me?

Thank you. Cheers

ps: sorry if I have not expressed myself well, or it is not the right place.

**Comment by haraldg** [comment]
On 11.12.2020 23:45, preguntitas wrote:
> ```
> sh autogen.sh
> ./configure --enable-libusb --enable-drivers = all
> ```
>
> ```
> [preguntitas@Piccolo server]$ $PWD/LCDd -c LCDd.conf
> glcd: unknown ConnectionType: 'serdisplib'

Well, do you have serdisplib installed on you system?
Is it detected at the ./configure stage?

HTH,
Harald

**Comment by preguntitas** [comment]
I'm sorry,
I did not know that it had to be installed, separately, before compiling.

It is already working perfectly.

Thanks a lot. A greeting.
