### ISSUE TITLE
LCDproc crashing on pfSense, parsing issue?

### ISSUE THREAD

**Issue by TP-SpeeDj** [lcdproc/lcdproc#164]
[lcdproc_client.zip](https://github.com/lcdproc/lcdproc/files/5810017/lcdproc_client.zip)

PHP Warning:  Use of undefined constant i - assumed 'i' (this will throw an Error in a future version of PHP) in /usr/local/pkg/lcdproc_client.php on line 1257
PHP Warning:  Use of undefined constant i - assumed 'i' (this will throw an Error in a future version of PHP) in /usr/local/pkg/lcdproc_client.php on line 1270
PHP Warning:  Use of undefined constant i - assumed 'i' (this will throw an Error in a future version of PHP) in /usr/local/pkg/lcdproc_client.php on line 1283

The above lines are causing pfSense to report crashing on this module, any help would greatly be appreciated!

**Comment by ethandicks** [comment]
lcdproc_client.php is part of pfSense.  It's not in this repository.  LCDproc uses no PHP.

It needs to be updated at https://github.com/pfsense/FreeBSD-ports/blob/devel/sysutils/pfSense-pkg-LCDproc/files/usr/local/pkg/lcdproc_client.php
