### ISSUE TITLE
[Question] Matrix Orbital key protocol

### ISSUE THREAD

**Issue by vintagepc** [lcdproc/lcdproc#176]
Forgive the Noob question - I had a rummage around in the source and some datasheets and this isn't completely obvious to me right now. 

How are key events received or polled from Matrix orbital-type displays? Is it a poll to the primary serial interface itself or is it a composite USB device with a secondary channel for keystrokes?

To provide some context... I'm trying to determine whether it's possible to use https://www.adafruit.com/product/781 and alter the arduino source such that the outputs can be turned into a simple up/down/left/right keypad - and the first step to that is understanding how the protocol reports keys. The 2041 datasheet from Matrix isn't particularly helpful as they only mention enabling/disabling autopoll, not the command sent to report a press or the command to poll key state. :-/

**Comment by ethandicks** [comment]
There is only one communication channel (RS-232 or USB) for Matrix Orbital displays.  Commands and responses go over the same channel.  The keypad isn't separate.

**Comment by vintagepc** [comment]
Thanks for the reply. So looking at https://github.com/lcdproc/lcdproc/blob/master/server/drivers/MtxOrb.c around line 1500, I gather the key input is literally just an incoming character from the device node. Seems pretty straightforward to do what I'm hoping to achieve then!

**Comment by vintagepc** [comment]
Sorry, forgot to follow up and close this. I did confirm it works as expected if the Teensy code scans a keymatrix and just returns characters over serial.

**Comment by ethandicks** [comment]
No worries.  I was checking other issues and saw this was resolved but unclosed.
