### ISSUE TITLE
Add process to convert docbook documentation to markdown (md) format

### ISSUE THREAD

**Issue by wilberforce** [lcdproc/lcdproc#3]
It would be great to add to the build process so that all of the docbook files are converted to .md so that the documentation could be ready directly on github.

**Comment by wilberforce** [comment]
oh - you might be well ahead here!

https://github.com/lcdproc/lcdproc-web

**Comment by willfe** [comment]
I'm going to try to get the website redone & hosted on Github Pages in the next few days. That's the stubby little skeleton I'm starting with; hopefully it makes the effort easier :)
