### ISSUE TITLE
Update of Change Log

### ISSUE THREAD

**Issue by wilberforce** [lcdproc/lcdproc#5]
For each pull request - Should a line be added to refer to the pull request?

https://github.com/lcdproc/lcdproc/blob/master/ChangeLog#L8

v0.5dev (ongoing development)
- Update hd44780-i2c driver, pins defined via config file, rather than hardcoded https://github.com/lcdproc/lcdproc/pull/1

v0.5.7

**Comment by wilberforce** [comment]
Should it be changed to ChangeLog.md so that links link above will work?

**Comment by willfe** [comment]
Well, I've renamed and updated the file, but it doesn't seem to be auto-linking to the pull requests for the three new entries I added :(

**Comment by wilberforce** [comment]
Thanks - looks good.

For the reference - use full path to the pull request:
`https://github.com/lcdproc/lcdproc/pull/1`

This then gets swapped out on view as #1 and auto links....
;-)

**Comment by wilberforce** [comment]
Hmm didn't work ;-(

https://github.com/lcdproc/lcdproc/blob/752abb7a1eb48b7792eb27fd1abc1605580009b7/ChangeLog.md

I'm not sure how - anyone?

**Comment by willfe** [comment]
Eh, I just ended up wrapping the URLs in parenthesis. Works well enough (it doesn't shorten the URLs, but it looks reasonably decent while still referencing the appropriate PRs.

**Comment by willfe** [comment]
Closing; feel free to reopen if we need to discuss further. Thanks!
