### ISSUE TITLE
ERROR: could not insert module /usr/local/lib/lcdproc/hd44780.so: Invalid module format

### ISSUE THREAD

**Issue by dagelf** [lcdproc/lcdproc#58]
This is for a ./configure &&make && sudo make install when trying to run with hd44780 on CHIP. This works fine for previous version.

**Comment by haraldg** [comment]
This should only happen if something went really wrong, e.g. if hd44780.so is an empty file. Maybe you tried to run "make install" after "make" failed once and now a corrupt file is lying around. After cleaning up /usr/local/lib/lcdproc things should work normal again.

**Comment by haraldg** [comment]
Closing as I think this issue was resolved. Please reopen and provide additional information, if this is wrong.
