### ISSUE TITLE
lcdproc reports impossible idle %

### ISSUE THREAD

**Issue by JamesGKent** [lcdproc/lcdproc#59]
I've compiled and am running version 0.5.8 on my raspberry pi 2 with a 40x4 display, as part of some testing I had the lcdproc client running and one of the screens (the first one after boot with default config) was reporting an idle time of 455%....

**Comment by haraldg** [comment]
Is this a data collecting error or a display problem? Can you check with the ncurses driver and different display sizes?

**Comment by haraldg** [comment]
The cpu screen got havily reworked in #120. Also no actual details about the problem have ever been provided. Thus closing this issue as obsolete. If there is still some problem, please reopen and provide additional information.
