### ISSUE TITLE
"unable to initialize GPIO pins" on Raspberry Pi 2 B+

### ISSUE THREAD

**Issue by kddlb** [lcdproc/lcdproc#84]
I built from the latest source (d6119a9) with `./configure --enable-drivers=hd44780`, and I get this error when trying to run LCDd:

```
pi@frambuesa:~/lcdproc $ sudo /etc/init.d/LCDd start
Starting LCDproc display server daemon: hd_init_gpio: unable to initialize GPIO pins
Driver [hd44780] init failed, return code -1
Could not load driver hd44780
There is no output driver
Critical error while initializing, abort.

```

**Comment by kddlb** [comment]
I changed the connection type from `gpio` to `raspberrypi`, and it "works" (I have no way to test it until I get an actual display 😅.) Will reopen when I'm able to test this properly...

**Comment by haraldg** [comment]
Looks to me like you just forgot to setup you pin mapping in the config file.

(The raspberrypi connection type has defaults, but the gpio connection type doesn't.)

**Comment by JamesGKent** [comment]
to use the gpio connection type you need to download and build/install the ugpio library as a dependency [https://github.com/mhei/libugpio](https://github.com/mhei/libugpio)

**Comment by kddlb** [comment]
@JamesGKent I took care of that.

@haraldg the documentation didn't  mention that, as far as I remember. I'll let you know in a few hours, when I get my LCD.

**Comment by kddlb** [comment]
I couldn't wait, so I propped up a tester thing using some LED's I had around, and it works using the `raspberrypi` driver with the default pinout assignments: https://www.youtube.com/watch?v=ipAzmZZczhI&feature=youtu.be
