### ISSUE TITLE
hd44780 not working on pi zero W

### ISSUE THREAD

**Issue by ElFishi** [lcdproc/lcdproc#86]
I can't get LCDproc to work with a HD44780 display on a Pi zero W. 
Hardware is OK as I can drive the display by a python script. 

LCDd reports 
`Server running in foreground`
`Listening for queries on 127.0.0.1:13666`
`HD44780: using ConnectionType: raspberrypi`
`hd44780: Using hd44780_default charmap`
`check_board_rev: Raspberry Pi 2 or higher detected`

I suspect the hardware detection and corresponding determination of GPIO base adress may be a problem here. Pi zero runs on the same SoC as a Pi 1, but is apprently treated as a "Pi2 or higher"

**Comment by terba** [comment]
This commit may be relevant: [https://github.com/WiringPi/WiringPi/commit/96344ff7125182989f98d3be8d111952a8f74e15](url)

**Comment by JamesGKent** [comment]
i agree this ought to be fixed, but the raspberrypi connection type is being depreciated in favor of the gpio connection type, assuming you have define all the pins in the config file can you try changing the connection type?

if you are using the default pins in the raspberrypi connection type but haven't declared them, add them into the config file first or this will not work.

**Comment by haraldg** [comment]
Which vesion of lcdproc?

As noted the raspberrypi cennection type is deprecated in favor or the gpio connection type. So this is not a valid issue IMO.

**Comment by terba** [comment]
It was compiled from github master branch at 2017-05-29

**Comment by terba** [comment]
I have to recompile then because gpio support was not compiled in. https://github.com/mhei/libugpio is the required library?

**Comment by haraldg** [comment]
Yes, the link is correct. Since you are recompiling, maybe you can give the release candidate a try?

**Comment by terba** [comment]
Of course, I will compile from master head. Thanks for the quick support!

**Comment by haraldg** [comment]
If possible, please compile from the release (candidate) tar ball. This tests the build system in a different way...

**Comment by terba** [comment]
OK

**Comment by terba** [comment]
I could compile and package it for piCore(Player) without any trouble. It works well with the gpio connection type on a rPi 1. Let's see if @ElFishi can use it on a Zero W. Thanks for the support.

**Comment by haraldg** [comment]
Thanks for your input.

**Comment by ElFishi** [comment]
I can confirm that LCDproc works with a Rapsberry Pi Zero W and ConnectionType=gpio.
